### ISSUE TITLE
Upgrade to 1.3.11

### ISSUE THREAD

**Issue by lreiher** [nobleo/paho.mqtt.c-release#2]
Hi,

Thanks for providing this library as a ROS package. Could you please upgrade to the latest version 1.3.11?

Our ROS package [mqtt_client](https://github.com/ika-rwth-aachen/mqtt_client) has shown performance issues with 1.3.10, also described in [this issue](https://github.com/eclipse/paho.mqtt.c/issues/1256).

Thanks in advance!

**Comment by Timple** [comment]
Sure thing:
https://github.com/ros/rosdistro/pull/34801
https://github.com/ros/rosdistro/pull/34802
https://github.com/ros/rosdistro/pull/34803
