### ISSUE TITLE
Upgrade to 1.3.12

### ISSUE THREAD

**Issue by cmraaron** [nobleo/paho.mqtt.c-release#3]
Hi,

Thanks for providing this library as a ROS package. Could you please upgrade to the latest version 1.3.12?
A lovely list of fixes re https://github.com/eclipse/paho.mqtt.c/milestone/19?closed=1

Cheers!

**Comment by Timple** [comment]
Sure: 
https://github.com/ros/rosdistro/pull/36230
https://github.com/ros/rosdistro/pull/36231

**Comment by cmraaron** [comment]
awesome thanks!  is it possible to get one for galactic too?

**Comment by Timple** [comment]
Galactic is deprecated: https://dlu.github.io/ros_clock/

So I don't think they accept PRs on it.

**Comment by cmraaron** [comment]
ah, of course, thanks.  
Over on https://github.com/nobleo/paho.mqtt.c-release/issues/1 I mentioned releases for 22.04, humble, which exist as native packages, but version is only 1.3.9.
what do you think about maintaining newer packages for that release?

**Comment by Timple** [comment]
I would not mind. But it's against policy to shadow existing binaries.

> In general you should not override or replace system dependencies from the system distribution with a package in the ROS distribution. 

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by Timple** [comment]
@cmraaron would you mind opening a ticket at the debian repo to upgrade to 1.3.12? It would be nice if these versions somehow are kept kind of equal.

Otherwise people meet a regression when upgrading to 22.04. That would be a bummer.
